name: DragonAntiPvPLeaver
author: IDragonfire, Serilum
version: 0.2
main: com.github.idragonfire.DragonAntiPvPLeaver.DAPL_Plugin
soft-depend: [WorldGuard, Factions]
    
permissions:
  dragonantipvpleaver.bypass:
    description: bypasses features