name: DragonAntiPvPLeaver
author: IDragonfire
version: 2.1.7.10
main: com.github.idragonfire.DragonAntiPvPLeaver.DAPL_Plugin
soft-depend: [WorldGuard, Factions, Vault]
    
permissions:
  dragonantipvpleaver.bypass:
    description: bypasses features